DECLARE
	MAX_RECORDID VARCHAR2 (255) ; 
	MAX_ALARMTIME TIMESTAMP ;
BEGIN
	SELECT MAX(RECORDID) INTO MAX_RECORDID FROM "YJ_WARNING_DIAGNOSIS" ; 
	SELECT MAX(ALARMTIME) INTO MAX_ALARMTIME FROM "YJ_WARNING_ALARMPIPE" ;

	-- 在诊断表中筛出发生故障的点送到报警表中
	INSERT INTO "YJ_WARNING_ALARMPIPE" (
		"DBID",
		"ACTIVE",
		"ALARMTIME",
		"FAULTDESC",
		"FAULTTYPE",
		"PROBABLITY",
		"PIPEID"
	) SELECT
		SEQ_YJ_WARNING_ALARMPIPE.nextval,
		'1',
		"CHECKTIME",
		"FAULTDESC",
		"FAULTTYPE",
		"PROBABLITY",
		"PIPEID"
	FROM
		"YJ_WARNING_DIAGNOSIS"
	WHERE
		-- 在诊断表中挑出recordid最大的（也就是最近一次诊断的结果）
		RECORDID = MAX_RECORDID
		-- 并且checktime不能与目标中相同，防止重复写入
		AND (CHECKTIME != MAX_ALARMTIME OR MAX_ALARMTIME IS NULL)
		-- 不正常的才写入预警
		AND ISNORMAL = '0'; 

END ;
/
